# Generated by Django 3.1.2 on 2020-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('starting_bid', models.IntegerField()),
                ('image', models.URLField(default='https://banner2.cleanpng.com/20180409/zrq/kisspng-post-it-note-paper-link-free-sticky-notes-clip-art-post-it-5acbacab077577.2543104915232974510306.jpg')),
            ],
        ),
    ]
