# Generated by Django 3.1.2 on 2020-11-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201102_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='person', to='auctions.Auction_Listings'),
        ),
    ]
