# Generated by Django 3.1.2 on 2020-10-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201027_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.IntegerField(max_length=16),
        ),
    ]
