# Generated by Django 3.1.2 on 2020-10-29 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201029_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
